### ISSUE TITLE
dirhtml builder does not work properly

### ISSUE THREAD

**Issue by robertodr** [thclark/sphinx-charts#16]
When using `dirhtml` as builder, everything appears to work fine. However, in pages other than `index.rst` the charts won't be shown. I suppose it's a path resolution issue, but couldn't really pinpoint where the problem is.

**Comment by thclark** [comment]
Hi @robertodr thanks for the issue. I've definitely used this for charts that don't appear in the `index` page. Can you provide a reproducible minimum example please?

**Comment by thclark** [comment]
Haven't had a response or any more information, so closing this. If someone comes across this, feel free to provide more information and I'll re-open the issue!

**Comment by robertodr** [comment]
So sorry I didn't reply earlier! Here is a reproducer repo: https://github.com/robertodr/issue-16-sphinx-charts The GitHub action compiles using the `dirhtml` builder and uploads to the `gh-pages`, which is then served here: https://robertodr.github.io/issue-16-sphinx-charts

The chart  in `index.rst` appears fine, but the one in `guide.rst` cannot be loaded: https://robertodr.github.io/issue-16-sphinx-charts/guide/
